### ISSUE TITLE
Super minor issue

### ISSUE THREAD

**Issue by DanShu15** [drewcassidy/KSP-DepthMask#1]
folder structure seems to be backwards for the PC version of the download

**Comment by wookieegoldberg** [comment]
The structure isn't backwards, the mod just doesn't need a folder inside GameData since it's a standalone DLL file. ModuleManager is the same way, a standalone DLL file that goes directly in GameData. The "DepthMask 1.0.0" directory isn't meant to go inside GameData, it's just the root directory of the zip. 

Similar example is ReStockPlus, where you have the root folder of the zip "ReStockPlus_0_1_3", then GameData (with modulemanager's DLL included), then the ReStockPlus folder:
![Screen Shot 2019-06-11 at 13 00 08](https://user-images.githubusercontent.com/37634584/59291520-15567680-8c49-11e9-8103-72ee9e03a3d5.png)

**Comment by DanShu15** [comment]
oh sweet!
Totally my mistake :)
